# A test workflow it will be changed to Dev & stage & prod once the steps are reviewed and approved.

name: test-CI

on:
  push:
    branches: [ "main" ]

  # manually run from the Actions tab
  workflow_dispatch:

jobs:
  # build the dotnet codebase
  build:
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
