# A test workflow it will be changed to Dev & stage & prod once the steps are reviewed and approved.

name: test-CI

on:
  push:
    branches: [ "main" ]

  # manually run from the Actions tab
  workflow_dispatch:

jobs:
  # build the dotnet codebase
  job-build:
    name: dotnet
    runs-on: windows-2022
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
