# A test workflow it will be changed to Dev & stage & prod once the steps are reviewed and approved.

name: CI-Comet.UI-test

on:
  push:
    branches: 
      # - main
      - test-pipeline
      # - Feature-DriverUtilities
      # - Dev
      # - Staging
  pull_request:
    branches:
      # - main
      - test-pipeline

  # manually run from the Actions tab
  workflow_dispatch: 

jobs:
  # build the dotnet codebase
  job-1:
    name: Dotnet Job
    runs-on: windows-2019

    env:
      DOTNET_MAIN_PROJ: 'IoT Apps\src\Comet.UI\Comet.UI.csproj'
      DOTNET_TEST_PROJ: 'IoT Apps\src\Comet.Tests.XUnit\Comet.Tests.XUnit.csproj'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_REF_NAME }}   # the branch that started the event e.g. test-pipeline

      - name: Install Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          # dotnet-quality: 'preview'

      - name: Install msbuild
        uses: microsoft/setup-msbuild@v1.1      

      - name: Restore proj
        run: msbuild /t:Restore /p:RestoreAdditionalProjectFallbackFolders="" "${{ env.DOTNET_MAIN_PROJ }}"
      
      - name: Build proj
        run: msbuild "${{ env.DOTNET_MAIN_PROJ }}" -property:Configuration=Release

      - name: Tests proj
        run: dotnet test "${{ env.DOTNET_TEST_PROJ }}"

      - name: Status
        run: |
          Get-ChildItem -Path Env: | Out-File -FilePath "IoT Apps\src\Comet.UI\bin\x86\Release\env.txt"
          dotnet --info | Out-File -FilePath "IoT Apps\src\Comet.UI\bin\x86\Release\dotnet-info.txt"
          tree | Out-File -FilePath "IoT Apps\src\Comet.UI\bin\x86\Release\tree.txt"

      #- name: Status
      #  run: |
      #    Get-ChildItem -Path Env:
      #    dotnet --info
      #    tree

