# A test workflow it will be changed to Dev & stage & prod once the steps are reviewed and approved.

name: CI-ReaderConsole-Dev

on:
  push:
    branches: 
      - main
      # - test-pipeline
      # - Feature-DriverUtilities
      # - Dev
      # - Staging
  pull_request:
    branches:
      # - main
      - Dev

  # manually run from the Actions tab
  workflow_dispatch: 

jobs:
  # build the dotnet codebase
  job-1:
    name: Dotnet Job
    runs-on: windows-2019

    env:
      COMET_MAIN_PROJ: 'Iot Apps\src\Comet.Apps.ReaderConsole\Comet.Apps.ReaderConsole.csproj'
      COMET_TEST_PROJ: 'Iot Apps\src\Comet.Tests.XUnit\Comet.Tests.XUnit.csproj'
      COMET_ARTIFACT_NAME: ReaderConsole-Windows-x64-${{ github.ref_name }}
      COMET_BUILD_PATH: 'Iot Apps/src/Comet.Apps.ReaderConsole/bin/debug/net7.0'
      COMET_STATUS_PATH: 'Iot Apps/src/Comet.Apps.ReaderConsole/bin/debug/status'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_REF_NAME }}

      - name: Install Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          # dotnet-quality: 'preview'  

      - name: Restore dependencies
        run: dotnet restore "${{ env.COMET_MAIN_PROJ }}"
      
      - name: Build proj
        run: dotnet build "${{ env.COMET_MAIN_PROJ }}" --no-restore

      - name: Tests proj
        run: dotnet test "${{ env.COMET_TEST_PROJ }}" --no-restore

      - name: Status
        run: |
          New-Item "${{ env.COMET_STATUS_PATH }}" -type Directory
          Get-ChildItem -Path Env: | Out-File -FilePath "${{ env.COMET_STATUS_PATH }}/env.txt"
          dotnet --info | Out-File -FilePath "${{ env.COMET_STATUS_PATH }}/dotnet-info.txt"
          tree | Out-File -FilePath "${{ env.COMET_STATUS_PATH }}/tree.txt"

      - name: save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.COMET_ARTIFACT_NAME }}
          path: |
            ${{ env.COMET_BUILD_PATH }}
            ${{ env.COMET_STATUS_PATH }}
