# A test workflow it will be changed to Dev & stage & prod once the steps are reviewed and approved.

name: CI-ReaderConsole-Dev

on:
  push:
    branches: 
      - main
      # - test-pipeline
      # - Feature-DriverUtilities
      # - Dev
      # - Staging
  pull_request:
    branches:
      # - main
      - Dev

  # manually run from the Actions tab
  workflow_dispatch: 

jobs:
  # build the dotnet codebase
  job-1:
    name: Dotnet Job
    runs-on: windows-2019

    env:
      COMET_MAIN_PROJ: 'Iot Apps\src\Comet.Apps.ReaderConsole\Comet.Apps.ReaderConsole.csproj'
      COMET_TEST_PROJ: 'Iot Apps\src\Comet.Tests.XUnit\Comet.Tests.XUnit.csproj'
      COMET_ARTIFACT_NAME: 'ReaderConsole- ${{ env.RUNNER_OS }} - ${{ env.RUNNER_ARCH }} - ${{ env.GITHUB_RUN_NUMBER }}'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_REF_NAME }}

      - name: Install Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          # dotnet-quality: 'preview'  

      - name: Restore dependencies
        run: dotnet restore "${{ env.COMET_MAIN_PROJ }}"
      
      - name: Build proj
        run: dotnet build "${{ env.COMET_MAIN_PROJ }}" --no-restore

      - name: Tests proj
        run: dotnet test "${{ env.COMET_TEST_PROJ }}"

      - name: Status file
        run: |
          New-Item "Status" -type Directory
          Get-ChildItem -Path Env: | Out-File -FilePath status\env.txt
          dotnet --info | Out-File -FilePath status\dotnet-info.txt
          tree | Out-File -FilePath status\tree.txt

      - name: save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.COMET_ARTIFACT_NAME }}
          path: 'Iot Apps/src/Comet.Apps.ReaderConsole/bin/debug/net7.0/'
     
      - name: Status 2
        run: |
          Get-ChildItem -Path Env:
          dotnet --info
          tree